number = float(input("Enter a number: "))
m1 = number * 1
m2 = number * 2
m3 = number * 3
m4 = number * 4
m5 = number * 5
m6 = number * 6
m7 = number * 7
m8 = number * 8
m9 = number * 9
m10 = number * 10
m11 = number * 11
m12 = number * 12
print("1 times",number,"=",m1)
print("2 times",number,"=",m2)
print("3 times",number,"=",m3)
print("4 times",number,"=",m4)
print("5 times",number,"=",m5)
print("6 times",number,"=",m6)
print("7 times",number,"=",m7)
print("8 times",number,"=",m8)
print("9 times",number,"=",m9)
print("10 times",number,"=",m10)
print("11 times",number,"=",m11)
print("12 times",number,"=",m12)