number = float(input("Enter a number: "))
m1 = number ** 1
m2 = number ** 2
m3 = number ** 3
m4 = number ** 4
m5 = number ** 5
m6 = number ** 6
m7 = number ** 7
m8 = number ** 8
m9 = number ** 9
m10 = number ** 10
m11 = number ** 11
m12 = number ** 12
print(number,"to the power of 1 =",m1)
print(number,"to the power of 2 =",m2)
print(number,"to the power of 3 =",m3)
print(number,"to the power of 4 =",m4)
print(number,"to the power of 5 =",m5)
print(number,"to the power of 6 =",m6)
print(number,"to the power of 7 =",m7)
print(number,"to the power of 8 =",m8)
print(number,"to the power of 9 =",m9)
print(number,"to the power of 10 =",m10)
print(number,"to the power of 11 =",m11)
print(number,"to the power of 12 =",m12)